{
 "title": "Device Data - QuestDB Demo",
 "description": "Sending synthetic data from sensors",
 "time": { "from": "now-5s", "to": "now" },
 "refresh": "500s",
 "panels": [
  { "title": "Measure1 and Measure2 samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Measures sampled by 30 seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\", device_type,\n  avg(measure1) AS metric,\n  avg(measure2) as m2\nFROM iot_data\nWHERE\n  $__timeFilter(timestamp)\nsample by 30s \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Measures sampled by minute, stacked",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\", device_type,\n  avg(measure1) AS metric,\n  avg(measure2) as m2\nFROM iot_data\nWHERE\n  $__timeFilter(timestamp)\nsample by 1m \nORDER BY 1,2"
    }
   ]
  },
  { "title": "Speed and location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average Speeds",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  device_type,\n  avg(speed) as avg_speed\nFROM iot_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of data points received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH in_interval AS (\nSELECT count(*) as total_in_interval\nFROM iot_data\nWHERE\n  $__timeFilter(timestamp)\n  ), absolute_total AS (\n  SELECT count(*) as total_seen\nFROM iot_data\n  )\n  select * from in_interval cross join absolute_total\n  \n"
    }
   ]
  },
  {
   "title": "Last seen position by device type",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 11, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "WITH average_vals AS (\n  select device_type, avg(duration_ms) as avg_duration_ms, avg(speed) as avg_speed, avg(measure1) as avg_m1, avg(measure2) as avg_m2 from iot_data \n  WHERE\n  $__timeFilter(timestamp)\n), latest_seen AS (\nselect timestamp, device_type, lat, lon  from 'iot_data' latest on timestamp partition by device_type)\nSelect timestamp as `time`, latest_seen.device_type as device_type, lat, lon, avg_duration_ms, avg_speed, avg_m1, avg_m2\nfrom latest_seen JOIN average_vals ON (device_type)\n\n"
    }
   ]
  },
  {
   "title": "Mean values",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "  select device_type, avg(duration_ms) as avg_duration_ms, avg(speed) as avg_speed, avg(measure1) as avg_m1, avg(measure2) as avg_m2 from iot_data \n  WHERE\n  $__timeFilter(timestamp)\n\n"
    }
   ]
  }
 ]
}