{
 "title": "Fixed Income Securities Demo",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "250ms",
 "templating": {
  "list": [
   {
    "name": "CUSIP",
    "label": "CUSIP",
    "query": "select distinct cusip from Treasury_Securities"
   },
   {
    "name": "SecurityTypes",
    "label": "SecurityTypes",
    "query": "SELECT distinct Security_Type from Treasury_Securities"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest CUSIP values",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp time, CUSIP, BidPrice, AskPrice, Venue, datediff('s', timestamp, now()) as secs_ago from UST_prices \nwhere $__timeFilter(timestamp)\nLATEST ON timestamp PARTITION BY CUSIP order by timestamp desc;\n\n",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Latest Security Terms",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp time, Security_Term, BidPrice, AskPrice, Venue, datediff('s', timestamp, now()) as secs_ago from UST_prices \nwhere $__timeFilter(timestamp)\nLATEST ON timestamp PARTITION BY Security_Term order by timestamp desc;\n\n",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Yesterday's VWAP - CUSIP ${CUSIP}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH single_cusip AS (\n    SELECT \n          timestamp,  CUSIP, \n          SUM(Qty) AS volume, \n          SUM(price * Qty) AS traded_value\n     FROM UST_trades\n     WHERE timestamp IN yesterday()\n     AND CUSIP = '${CUSIP}'\n     SAMPLE BY 5m\n), cumulative AS ( \n     SELECT timestamp time, CUSIP, \n           SUM(traded_value)\n                OVER (ORDER BY timestamp) AS cumulative_value,\n           SUM(volume)\n                OVER (ORDER BY timestamp) AS cumulative_volume\n     FROM single_cusip\n)\nSELECT time, cumulative_value/cumulative_volume AS vwap FROM cumulative; \n\n\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Operations by Security Type - ${SecurityTypes}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select timestamp time, Security_Type, count() AS total from UST_prices \njoin Treasury_Securities ON (CUSIP, Security_Term)\nwhere $__timeFilter(timestamp) AND Security_Type IN (${SecurityTypes})\nsample by $__sampleByInterval FILL (PREV)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Today's VWAP - CUSIP ${CUSIP}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH single_cusip AS (\n    SELECT \n          timestamp,  CUSIP, \n          SUM(Qty) AS volume, \n          SUM(price * Qty) AS traded_value\n     FROM UST_trades\n     WHERE timestamp IN today()\n     AND CUSIP = '${CUSIP}'\n     SAMPLE BY 5m\n), cumulative AS ( \n     SELECT timestamp time, CUSIP, \n           SUM(traded_value)\n                OVER (ORDER BY timestamp) AS cumulative_value,\n           SUM(volume)\n                OVER (ORDER BY timestamp) AS cumulative_volume\n     FROM single_cusip\n)\nSELECT time, cumulative_value/cumulative_volume AS vwap FROM cumulative; \n\n\n"
    }
   ]
  },
  {
   "title": "Mid price - CUSIP ${CUSIP}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select t.timestamp time, t.CUSIP, avg(price) as price, avg(askPrice) as ask, avg(bidPrice) as bid\nfrom ust_trades t asof join ust_prices\nwhere $__timeFilter(t.timestamp) AND t.CUSIP = '${CUSIP}'\nsample by $__sampleByInterval FILL (PREV)\n\n\n"
    }
   ]
  },
  {
   "title": "OHLC - 3 mins - CUSIP ${CUSIP}",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, first(price) as open, last(price) as close, min(price) as lo, max(price) as hi, sum(qty) as vol\nFROM UST_trades\nWHERE CUSIP = '${CUSIP}' and \n$__timeFilter(timestamp) \nSAMPLE BY 2m ALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  }
 ]
}