{
 "title": "GitHub Events Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Number of Events Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time, count(*) FROM github_events WHERE\n  $__timeFilter(timestamp) GROUP BY timestamp  ORDER BY timestamp;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Event Types Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT type, count(*) as total FROM github_events WHERE\n  $__timeFilter(timestamp) GROUP BY type;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Events Per Repository",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT repo, count(*) as total FROM github_events WHERE\n  $__timeFilter(timestamp) GROUP BY repo order by total desc limit 10;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Top Actors",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT actor, count(*) as total FROM github_events WHERE\n  $__timeFilter(timestamp) GROUP BY actor ORDER BY total DESC LIMIT 10;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Events Count by Type and Repository",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, type, count(*) as total FROM github_events \nWHERE\n  $__timeFilter(timestamp)\nsample by 15s;",
     "selectedFormat": 2
    }
   ]
  }
 ]
}