{
 "title": "Parallel data demo",
 "description": "Sending synthetic data from sensors",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"*\" FROM \"iot_data\" WHERE  $__timeFilter(timestamp) LIMIT -20",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Measures sampled by 10 seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\", device_type,\n  avg(measure1) AS metric,\n  avg(measure2) as m2\nFROM iot_data\nWHERE\n  $__timeFilter(timestamp)\nsample by 10s \nORDER BY 1,2",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "data points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Number of data points received",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH in_interval AS (\nSELECT count(*) as total_in_interval\nFROM iot_data\nWHERE\n  $__timeFilter(timestamp)\n  ), absolute_total AS (\n  SELECT count(*) as total_seen\nFROM iot_data\n  )\n  select * from in_interval cross join absolute_total\n  \n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Ingestion per second",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time,  count() rate_sec FROM \"iot_data\" \nSAMPLE BY 1s FROM $__fromTime TO $__toTime FILL(NULL) LIMIT -20",
     "selectedFormat": 2
    }
   ]
  }
 ]
}