{
 "title": "Factory Sensors - QuestDB Demo",
 "description": "Sending synthetic data from sensors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "500s",
 "panels": [
  { "title": "Measure1 and Measure2 samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Measures sampled by 30 seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\", address,\n  avg(value) AS metric,  \nFROM plant_sensors\nWHERE value is not null and \n  $__timeFilter(timestamp)\nsample by 30s \nORDER BY 1,2",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Measures sampled by minute, stacked",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\", address,\n  avg(value) AS metric\nFROM plant_sensors\nWHERE value is not null and \n  $__timeFilter(timestamp)\nsample by 1m \nORDER BY 1,2",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "Speed and location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average Speeds",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  system,\n  avg(value) as avg_value\nFROM plant_sensors\nWHERE value is not null and \n  $__timeFilter(timestamp)\nORDER BY 1",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Mean values",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "  select system, avg(value) from plant_sensors \n  WHERE value is not null and \n  $__timeFilter(timestamp)\n\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Number of data points received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH in_interval AS (\nSELECT count(*) as total_in_interval\nFROM plant_sensors\nWHERE\n  $__timeFilter(timestamp)\n  ), absolute_total AS (\n  SELECT count(*) as total_seen\nFROM plant_sensors\n  )\n  select * from in_interval cross join absolute_total\n  \n",
     "selectedFormat": 2
    }
   ]
  }
 ]
}