{
 "title": "smart-meters",
 "time": { "from": "now-5m", "to": "now-0m" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH in_interval AS (\nSELECT count(*) as events_in_interval,\ncount_distinct(device_id) as devices_in_interval\nFROM smart_meters\nWHERE\n  $__timeFilter(timestamp)\n  ), absolute_total AS (\n  SELECT count(*) as total_events,\n  count_distinct(device_id) as total_devices\nFROM smart_meters\n  )\n  select events_in_interval, total_events, devices_in_interval, total_devices from in_interval cross join absolute_total",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, count()\nfrom smart_meters where $__timeFilter(timestamp) \nand timestamp < timestamp_floor('s', now())\nsample by 10s\nlimit 600",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, avg(energy_consumption) as avg_consumption, max(energy_consumption) as max_consumption, min(energy_consumption) as min_consumption\nfrom smart_meters where $__timeFilter(timestamp) \nsample by 1s\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, avg(power_factor) as avg_power_factor, max(power_factor) as max_power_factor, min(power_factor) as min_power_factor\nfrom smart_meters where $__timeFilter(timestamp) \nsample by 1s\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT *\nfrom smart_meters where $__timeFilter(timestamp) \nlimit -10\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Device status in 30s intervals",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,  \nSUM(CASE WHEN status='Active' THEN 1 ELSE 0 END) as Active, \nSUM(CASE WHEN status='Inactive' THEN 1 ELSE 0 END) as Inactive,\nSUM(CASE WHEN status='Faulty' THEN 1 ELSE 0 END) as Faulty,\ncount() as total\nfrom smart_meters where $__timeFilter(timestamp) \nsample by 30s\norder by timestamp desc\nlimit 8\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Consumption for AAA000 vs AAA0010",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,device_id, avg(energy_consumption) as avg_consumption\nfrom smart_meters where $__timeFilter(timestamp) and device_id IN ('AAA0000', 'AAA0010')\nsample by 1s\n",
     "selectedFormat": 2
    }
   ]
  }
 ]
}